---
title: "CAIClean"
author: "Lauren Moore"
date: "2/22/2023"
output: github_document
---

```{r}
#load packages
library(tidyverse) # I literally don't know how anyone uses R without this.
#library(readxl) # For reading Excel files
library(usdata) # has a nice function for converting state abbreviations to state names and vis versa
#library(utils) # Utilities. Used to unzip a download.
```

```{r}
#file content
fileList <- list.files(path="./RawData", pattern="*.csv")
addPath <- function(x){paste0("./RawData/",x)}
pathList <- lapply(fileList, addPath)
fileContent <- lapply(pathList, read.csv)
```

```{r}
#import all files
ChildCareCenters <- fileContent[[1]]
CollegesAndUniversities <- fileContent[[2]]
Courthouses <- fileContent[[3]]
ExtensionOffices <- fileContent[[4]] #already cleaned; has some lat and long but not all
FireStations <- fileContent[[5]]
LibrariesFromTilson <- fileContent[[6]] #already cleaned
Churches <- fileContent[[7]]
LibrariesSurvey <- fileContent[[8]]
PollingLocations <- fileContent[[11]]
PublicSchoolsK12 <- fileContent[[12]]
SupplementalColleges <- fileContent[[13]]
```

```{r}
#clean Child Care Centers
cleanChildCareCenters <- 
    ChildCareCenters %>%
      select(
        -OBJECTID,
        -ID,
        -ZIP4,
        -TELEPHONE,
        -POPULATION,
        -COUNTRY,
        -NAICS_CODE,
        -SOURCE,
        -SOURCEDATE,
        -VAL_METHOD,
        -VAL_DATE,
        -WEBSITE,
        -ST_SUBTYPE,
        -X,
        -Y,
        -NAICS_DESC
      ) %>% 
      filter(STATE=="WV") %>%
      filter(TYPE!="RELIGIOUS FACILITY") %>%
      filter(TYPE!="CENTER BASED") %>% #only want school based and head start
      filter(STATUS=="OPEN") %>% #only want open centers
      mutate(COUNTYFIPSCHAR=paste0("_",as.character(COUNTYFIPS),sep="")) %>%
      mutate(LOCATIONTYPE="Child Care Center") %>%
      select(
        -TYPE,
        -STATUS,
        -COUNTYFIPS
      ) %>%
      na.omit()
```


```{r}
#clean colleges and universities
cleanCollegeUniversity <- 
    CollegesAndUniversities %>%
      select(
        -X,
        -Y,
        -OBJECTID,
        -IPEDSID,
        -ZIP4,
        -TELEPHONE,
        -POPULATION,
        -COUNTRY,
        -NAICS_CODE,
        -SOURCE,
        -SOURCEDATE,
        -VAL_METHOD,
        -VAL_DATE,
        -WEBSITE,
        -STFIPS,
        -COFIPS,
        -SECTOR,
        -LEVEL_,
        -HI_OFFER,
        -DEG_GRANT,
        -LOCALE,
        -CLOSE_DATE,
        -MERGE_ID,
        -ALIAS,
        -SIZE_SET,
        -INST_SIZE,
        -PT_ENROLL,
        -FT_ENROLL,
        -TOT_ENROLL,
        -HOUSING,
        -DORM_CAP,
        -TOT_EMP,
        -SHELTER_ID,
        -NAICS_DESC
      ) %>% 
      filter(STATE=="WV") %>%
      filter(TYPE==1) %>% #public schools
      mutate(COUNTYFIPSCHAR=paste0("_",as.character(COUNTYFIPS),sep="")) %>%
      mutate(LOCATIONTYPE="Universities and Tech Schools") %>%
      select(
        -TYPE,
        -STATUS,
        -COUNTYFIPS
      ) %>%
      na.omit()
```

```{r}
#clean courthouses
cleanCourthouse <- 
    Courthouses %>%
      select(
        -PERMANENT_IDENTIFIER,
        -SOURCE_FEATUREID,
        -SOURCE_DATASETID,
        -SOURCE_DATADESC,
        -SOURCE_ORIGINATOR,
        -DATA_SECURITY,
        -DISTRIBUTION_POLICY,
        -LOADDATE,
        -FTYPE,
        -FCODE,
        -ISLANDMARK,
        -POINTLOCATIONTYPE,
        -ADMINTYPE,
        -ADDRESSBUILDINGNAME,
        -GNIS_ID,
        -FOOT_ID,
        -COMPLEX_ID,
        -GLOBALID,
        -X,
        -Y,
        -OBJECTID
      ) %>% 
      filter(STATE=="WV") %>%
      mutate(COUNTY=NA) %>%
      mutate(LATITUDE=NA) %>%
      mutate(LONGITUDE=NA) %>%
      mutate(COUNTYFIPSCHAR=NA) %>%
      mutate(ZIP=ZIPCODE) %>%
      mutate(LOCATIONTYPE="Courthouse") %>%
      select(
        NAME,
        ADDRESS,
        CITY,
        STATE,
        ZIP,
        COUNTY,
        LATITUDE,
        LONGITUDE,
        COUNTYFIPSCHAR,
        LOCATIONTYPE
      )
      #na.omit()
```

```{r}
#clean fire stations
cleanFireStations <- 
    FireStations %>%
      select(
        -PERMANENT_IDENTIFIER,
        -SOURCE_FEATUREID,
        -SOURCE_DATASETID,
        -SOURCE_DATADESC,
        -SOURCE_ORIGINATOR,
        -DATA_SECURITY,
        -DISTRIBUTION_POLICY,
        -LOADDATE,
        -FTYPE,
        -FCODE,
        -ISLANDMARK,
        -POINTLOCATIONTYPE,
        -ADMINTYPE,
        -ADDRESSBUILDINGNAME,
        -GNIS_ID,
        -FOOT_ID,
        -COMPLEX_ID,
        -GLOBALID,
        -X,
        -Y,
        -OBJECTID
      ) %>% 
      filter(STATE=="WV") %>%
      mutate(COUNTY=NA) %>%
      mutate(LATITUDE=NA) %>%
      mutate(LONGITUDE=NA) %>%
      mutate(COUNTYFIPSCHAR=NA) %>%
      mutate(ZIP=ZIPCODE) %>%
      mutate(LOCATIONTYPE="Courthouse") %>%
      select(
        NAME,
        ADDRESS,
        CITY,
        STATE,
        ZIP,
        COUNTY,
        LATITUDE,
        LONGITUDE,
        COUNTYFIPSCHAR,
        LOCATIONTYPE
      )
      #na.omit()
```

```{r}
#clean places of worship
cleanChurches <-
  Churches %>%
      select(
        NAME,
        STREET,
        CITY,
        STATE,
        ZIP
      ) %>% 
      filter(STATE=="WV") %>%
      mutate(COUNTY=NA) %>%
      mutate(LATITUDE=NA) %>%
      mutate(LONGITUDE=NA) %>%
      mutate(COUNTYFIPSCHAR=NA) %>%
      mutate(ADDRESS=STREET) %>%
      mutate(LOCATIONTYPE="Place of Worship") %>%
      select(
        NAME,
        ADDRESS,
        CITY,
        STATE,
        ZIP,
        COUNTY,
        LATITUDE,
        LONGITUDE,
        COUNTYFIPSCHAR,
        LOCATIONTYPE
      )
      #na.omit()

#https://towardsdatascience.com/breaking-down-geocoding-in-r-a-complete-guide-1d0f8acd0d4b
#https://hifld-geoplatform.opendata.arcgis.com/datasets/geoplatform::all-places-of-worship/explore?filters=eyJTVEFURSI6WyJXViJdfQ%3D%3D&location=38.762635%2C-80.138550%2C8.00
```

```{r}
#clean libraries from survey data for cross reference
cleanLibrarySurvey <-
  LibrariesSurvey %>%
      select(
        LIBNAME,
        ADDRESS,
        CITY,
        ZIP,
        STABR,
        LONGITUD,
        LATITUDE
      ) %>% 
      filter(STABR=="WV") %>%
      mutate(STATE=STABR) %>%
      mutate(COUNTY=NA) %>%
      mutate(LATITUDE=NA) %>%
      mutate(LONGITUDE=NA) %>%
      mutate(COUNTYFIPSCHAR=NA) %>%
      mutate(NAME=LIBNAME) %>%
      mutate(LOCATIONTYPE="Library") %>%
      select(
        NAME,
        ADDRESS,
        CITY,
        STATE,
        ZIP,
        COUNTY,
        LATITUDE,
        LONGITUDE,
        COUNTYFIPSCHAR,
        LOCATIONTYPE
      )
      #na.omit()
```

```{r}
#clean polling locations
cleanPollingLocations <- 
    PollingLocations %>%
      select(
        -election_date,
        -jurisdiction,
        -jurisdiction_type,
        -precinct_id,
        -precinct_name,
        -polling_place_id,
        -location_type,
        -notes,
        -source,
        -source_date,
        -source_notes,
        -X
      ) %>%
      filter(state=="WV") %>%
      separate(address, into=c("ADDRESS", "CITY", "STATEZIP"), sep=",") %>%
      separate(STATEZIP, into=c("delete", "STATE", "ZIP"), sep=" ") %>%
      mutate(COUNTY=county_name) %>%
      mutate(LATITUDE=NA) %>%
      mutate(LONGITUDE=NA) %>%
      mutate(COUNTYFIPSCHAR=NA) %>%
      mutate(LOCATIONTYPE="Polling Location") %>%
      mutate(NAME=name) %>%
      select(
        NAME,
        ADDRESS,
        CITY,
        STATE,
        ZIP,
        COUNTY,
        LATITUDE,
        LONGITUDE,
        COUNTYFIPSCHAR,
        LOCATIONTYPE
      )
      #na.omit()
```

```{r}
#clean public schools k12
cleanPublicSchoolsK12 <- 
    PublicSchoolsK12 %>%
      select(
        NAME,
        ADDRESS,
        CITY,
        STATE,
        ZIP,
        COUNTY,
        COUNTYFIPS,
        LATITUDE,
        LONGITUDE
      ) %>% 
      filter(STATE=="WV") %>%
      mutate(COUNTYFIPSCHAR=paste0("_",as.character(COUNTYFIPS),sep="")) %>%
      mutate(LOCATIONTYPE="K12 Public School") %>%
      select(
        NAME,
        ADDRESS,
        CITY,
        STATE,
        ZIP,
        COUNTY,
        LATITUDE,
        LONGITUDE,
        COUNTYFIPSCHAR,
        LOCATIONTYPE
      )
      #na.omit()
```

```{r}
#clean supplemental colleges
cleanSupplementalColleges <- 
    SupplementalColleges %>%
      select(
        NAME,
        ADDRESS,
        CITY,
        STATE,
        ZIP,
        TYPE,
        STATUS,
        COUNTY,
        COUNTYFIPS,
        LATITUDE,
        LONGITUDE
      ) %>% 
      filter(STATE=="WV") %>%
      mutate(COUNTYFIPSCHAR=paste0("_",as.character(COUNTYFIPS),sep="")) %>%
      mutate(LOCATIONTYPE="Community College") %>%
      select(
        NAME,
        ADDRESS,
        CITY,
        STATE,
        ZIP,
        COUNTY,
        LATITUDE,
        LONGITUDE,
        COUNTYFIPSCHAR,
        LOCATIONTYPE
      )
      #na.omit()
```

```{r}
cleanish <-
  cleanChildCareCenters %>%
  rbind(cleanCollegeUniversity) %>%
  rbind(cleanCourthouse) %>%
  rbind(cleanFireStations) %>%
  rbind(cleanChurches) %>%
  rbind(cleanLibrarySurvey) %>%
  rbind(cleanPollingLocations) %>%
  rbind(cleanPublicSchoolsK12) %>%
  rbind(cleanSupplementalColleges) %>%
  distinct(NAME)

write.csv(cleanish, "cleanish.csv")
```

```{r}

```



